config/routes.rb
Rails.application.routes.draw do
  resources :horse_details
  resources :horses
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/horse.rb
class Horse < ApplicationRecord
  has_many :horse_details
end

app/models/horse_detail.rb
class HorseDetail < ApplicationRecord
  belongs_to :horse
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/horse_details_controller.rb
class HorseDetailsController < ApplicationController
  before_action :set_horse_detail, only: %i[ show edit update destroy ]

  # GET /horse_details or /horse_details.json
  def index
    @horse_details = HorseDetail.all
  end

  # GET /horse_details/1 or /horse_details/1.json
  def show
  end

  # GET /horse_details/new
  def new
    @horse_detail = HorseDetail.new
  end

  # GET /horse_details/1/edit
  def edit
  end

  # POST /horse_details or /horse_details.json
  def create
    @horse_detail = HorseDetail.new(horse_detail_params)

    respond_to do |format|
      if @horse_detail.save
        format.html { redirect_to horse_detail_url(@horse_detail), notice: "Horse detail was successfully created." }
        format.json { render :show, status: :created, location: @horse_detail }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @horse_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /horse_details/1 or /horse_details/1.json
  def update
    respond_to do |format|
      if @horse_detail.update(horse_detail_params)
        format.html { redirect_to horse_detail_url(@horse_detail), notice: "Horse detail was successfully updated." }
        format.json { render :show, status: :ok, location: @horse_detail }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @horse_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /horse_details/1 or /horse_details/1.json
  def destroy
    @horse_detail.destroy

    respond_to do |format|
      format.html { redirect_to horse_details_url, notice: "Horse detail was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_horse_detail
      @horse_detail = HorseDetail.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def horse_detail_params
      params.fetch(:horse_detail, {})
    end
end

app/controllers/horses_controller.rb
class HorsesController < ApplicationController
  before_action :set_horse, only: %i[ show edit update destroy ]

  # GET /horses or /horses.json
  def index
    @horses = Horse.all
  end

  # GET /horses/1 or /horses/1.json
  def show
  end

  # GET /horses/new
  def new
    @horse = Horse.new
  end

  # GET /horses/1/edit
  def edit
  end

  # POST /horses or /horses.json
  def create
    @horse = Horse.new(horse_params)

    respond_to do |format|
      if @horse.save
        format.html { redirect_to horse_url(@horse), notice: "Horse was successfully created." }
        format.json { render :show, status: :created, location: @horse }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @horse.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /horses/1 or /horses/1.json
  def update
    respond_to do |format|
      if @horse.update(horse_params)
        format.html { redirect_to horse_url(@horse), notice: "Horse was successfully updated." }
        format.json { render :show, status: :ok, location: @horse }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @horse.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /horses/1 or /horses/1.json
  def destroy
    @horse.destroy

    respond_to do |format|
      format.html { redirect_to horses_url, notice: "Horse was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_horse
      @horse = Horse.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def horse_params
      params.fetch(:horse, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/horse_details_helper.rb
module HorseDetailsHelper
end

app/helpers/horses_helper.rb
module HorsesHelper
end

app/views/horse_details/_form.html.erb
<%= form_with(model: horse_detail) do |form| %>
  <% if horse_detail.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(horse_detail.errors.count, "error") %> prohibited this horse_detail from being saved:</h2>

      <ul>
        <% horse_detail.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/horse_details/_horse_detail.html.erb
<div id="<%= dom_id horse_detail %>">
</div>

app/views/horse_details/edit.html.erb
<h1>Editing horse detail</h1>

<%= render "form", horse_detail: @horse_detail %>

<br>

<div>
  <%= link_to "Show this horse detail", @horse_detail %> |
  <%= link_to "Back to horse details", horse_details_path %>
</div>

app/views/horse_details/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Horse details</h1>

<div id="horse_details">
  <% @horse_details.each do |horse_detail| %>
    <%= render horse_detail %>
    <p>
      <%= link_to "Show this horse detail", horse_detail %>
    </p>
  <% end %>
</div>

<%= link_to "New horse detail", new_horse_detail_path %>

app/views/horse_details/new.html.erb
<h1>New horse detail</h1>

<%= render "form", horse_detail: @horse_detail %>

<br>

<div>
  <%= link_to "Back to horse details", horse_details_path %>
</div>

app/views/horse_details/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @horse_detail %>

<div>
  date: <%= @horse_detail.date %><br>
  weather: <%= @horse_detail.weather %><br>
  race_name: <%= @horse_detail.race_name %><br>
  ranking: <%= @horse_detail.ranking %><br>
  popularity: <%= @horse_detail.popularity %><br>
  jockey: <%= @horse_detail.jockey %><br>
  race_condition: <%= @horse_detail.race_condition %><br>
  race_distance: <%= @horse_detail.race_distance %><br>
  time: <%= @horse_detail.time %><br>
  dressing_difference_time: <%= @horse_detail.dressing_difference_time %><br>
  body_weight: <%= @horse_detail.body_weight %>
</div>

<div>
  <%= link_to "horse", horse_path(@horse_detail.horse) %> |
  <%= link_to "Edit this horse detail", edit_horse_detail_path(@horse_detail) %> |
  <%= link_to "Back to horse details", horse_details_path %>

  <%= button_to "Destroy this horse detail", @horse_detail, method: :delete %>
</div>

app/views/horses/_form.html.erb
<%= form_with(model: horse) do |form| %>
  <% if horse.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(horse.errors.count, "error") %> prohibited this horse from being saved:</h2>

      <ul>
        <% horse.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/horses/_horse.html.erb
<div id="<%= dom_id horse %>">
</div>

app/views/horses/edit.html.erb
<h1>Editing horse</h1>

<%= render "form", horse: @horse %>

<br>

<div>
  <%= link_to "Show this horse", @horse %> |
  <%= link_to "Back to horses", horses_path %>
</div>

app/views/horses/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Horses</h1>

<div id="horses">
  <% @horses.each do |horse| %>
    <%= render horse %>
    <p>
      <%= link_to "Show this #{horse.name}", horse %>
    </p>
  <% end %>
</div>

<%= link_to "New horse", new_horse_path %>

app/views/horses/new.html.erb
<h1>New horse</h1>

<%= render "form", horse: @horse %>

<br>

<div>
  <%= link_to "Back to horses", horses_path %>
</div>

app/views/horses/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @horse %>

<div>
  name: <%= @horse.name %>
  <br>
  url: <%= @horse.url %>
</div>

<div>
  <% @horse.horse_details.each do |horse_detail| %>
    <%= link_to "horse_detail link (id: #{horse_detail.id})", horse_detail_path(horse_detail) %>
    <br>
  <% end %>
  <%= link_to "Edit this horse", edit_horse_path(@horse) %> |
  <%= link_to "Back to horses", horses_path %>

  <%= button_to "Destroy this horse", @horse, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HorseRacing</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>